(() => {
'use strict';
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
let latest,graphKey='',forestCache;
const labels={pair:['Pair two defects','Follow two odd regions until they meet, then peel the connecting tree.'],reactivate:['An even cluster grows again','Watch a paused, even cluster become odd when a third defect joins it.'],boundary:['Reach an allowed boundary','One defect can be explained by a path ending at an unconstrained boundary.'],forest:['The forest changes the answer','Try the forest selector below: the same grown region can yield 5 or 3 edges.'],clustering:['A limit of cluster growth','Even the best forest cannot recover a correction outside the grown region.'],custom:['Your own syndrome','Choose detector events, allow a boundary if needed, and inspect every decision.']};
const strategyNames={'bfs':'Breadth-first','reverse-bfs':'Reversed breadth-first','dfs':'Depth-first'};
function svgEl(tag,attrs,text,parent){const e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;parent.append(e);return e;}
function path(start,parents){const p=[start];while(parents[p.at(-1)]!==p.at(-1)&&p.length<parents.length+1)p.push(parents[p.at(-1)]);return p;}
function drawPath(){
 if(!latest)return;const {s,graph}=latest,svg=$('dsu-path');svg.replaceChildren();
 let selected=$('dsu-node').value==='auto'?(s.operations.at(-1)?.a??s.focusNodes[0]??graph.nodes.find(v=>v.syndrome)?.id??0):Number($('dsu-node').value);
 const op=s.micro?s.operations.at(-1):null,before=op?.parentsBefore||s.parents,after=s.parents;
 const rows=op?[['Before',path(selected,before)],['Now',path(selected,after)]]:[['Parents',path(selected,after)]];
 const width=Math.max(260,svg.getBoundingClientRect().width),x0=72,gap=Math.min(80,(width-x0-28)/Math.max(1,...rows.map(r=>r[1].length-1)));
 const height=op?145:85;svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.setAttribute('height',height);svg.style.minHeight=height+'px';
 const defs=svgEl('defs',{},undefined,svg),marker=svgEl('marker',{id:'parent-arrow',viewBox:'0 0 10 10',refX:8,refY:5,markerWidth:5,markerHeight:5,orient:'auto-start-reverse'},undefined,defs);svgEl('path',{d:'M 0 0 L 10 5 L 0 10 z',fill:'var(--muted-foreground)'},undefined,marker);
 rows.forEach(([label,ids],row)=>{const y=42+row*65;svgEl('text',{x:0,y:y+4,fill:'var(--muted-foreground)','font-size':12},label,svg);ids.forEach((id,i)=>{const x=x0+i*gap;if(i<ids.length-1)svgEl('line',{x1:x+19,x2:x+gap-23,y1:y,y2:y,stroke:'var(--muted-foreground)','stroke-width':1.4,'marker-end':'url(#parent-arrow)'},undefined,svg);const root=i===ids.length-1;svgEl('circle',{cx:x,cy:y,r:19,fill:root?'var(--accent)':'var(--background)',stroke:root?'var(--foreground)':'var(--border)','stroke-width':1},undefined,svg);svgEl('text',{x,y:y+4,'text-anchor':'middle',fill:'var(--foreground)','font-size':12},`v${id}`,svg);if(root)svgEl('text',{x,y:y+34,'text-anchor':'middle',fill:'var(--muted-foreground)','font-size':12},'root',svg);});});
 const changed=s.parents.filter((v,i)=>v!==before[i]).length;
 $('dsu-caption').textContent=op?`${s.action==='find'?'Find compressed':'This operation changed'} ${changed} parent pointer${changed===1?'':'s'}. ${op.same?'Both endpoint searches reach the same set.':`Endpoint roots before Union: v${op.ra} and v${op.rb}.`}`:`v${selected} belongs to the set represented by v${path(selected,s.parents).at(-1)}. Enable “Show every Find / Union” to see individual pointer changes.`;
 const array=$('parent-array');array.replaceChildren();for(const v of graph.nodes){const cell=document.createElement('div');cell.className='parent-cell'+(s.parents[v.id]===v.id?' root':'')+(s.parents[v.id]!==before[v.id]?' changed':'');cell.textContent=`${v.id} → ${s.parents[v.id]}`;array.append(cell);}
}
function residuals(){const {graph,s}=latest,input=graph.nodes.filter(v=>!v.boundary).map(v=>v.syndrome),boundary=graph.nodes.map(()=>0);for(const id of s.correction){const e=graph.edges[id];if(!graph.nodes[e.a].boundary)boundary[e.a]^=1;if(!graph.nodes[e.b].boundary)boundary[e.b]^=1;}const measured=graph.nodes.filter(v=>!v.boundary),endpoints=measured.map(v=>boundary[v.id]),residual=input.map((b,i)=>b^endpoints[i]);const rows=$('syndrome-rows');rows.replaceChildren();for(const [label,data]of [['Input s',input],['Edges ∂C',endpoints],['Residual r',residual]]){const row=document.createElement('div');row.className='syndrome-row';const name=document.createElement('span');name.className='syndrome-row-label';name.textContent=label;const strip=document.createElement('div');strip.className='bit-strip';data.forEach((b,i)=>{const cell=document.createElement('span');cell.className='bit-cell'+(b?' on':'')+((i+1)%7===0?' break':'');cell.textContent=b;cell.title=`v${i}: ${b}`;strip.append(cell);});const count=document.createElement('span');count.className='syndrome-count';count.textContent=data.reduce((a,b)=>a+b,0);row.append(name,strip,count);rows.append(row);}const valid=residual.every((b,i)=>b===s.bits[measured[i].id]),left=residual.reduce((a,b)=>a+b,0);$('invariant-status').textContent=valid?(left===0?'✓ All measured residuals are zero. The chosen edges reproduce the input syndrome.':`✓ Residual identity holds. ${left} measured bit${left===1?'':'s'} still need${left===1?'s':''} to be cleared.`):'Residual identity mismatch';}
function forestComparison(){const {graph,s,reference,grownReference,editing}=latest;const key=JSON.stringify([graph.nodes.map(v=>v.syndrome),graph.preset.boundary]);if(key!==graphKey){graphKey=key;forestCache=null;if(latest.fullTrace.valid){forestCache=Object.keys(strategyNames).map(f=>[f,globalThis.__ufLessonModel.run(graph,{forestStrategy:f})]);}const select=$('dsu-node'),old=select.value;select.replaceChildren(new Option('Current operation','auto'));for(const v of graph.nodes)select.append(new Option(`v${v.id}${v.label?' · defect '+v.label:''}${v.boundary?' · boundary':''}`,String(v.id)));if([...select.options].some(o=>o.value===old))select.value=old;}
 const body=$('forest-costs');body.replaceChildren();const reveal=['forest','peel','done'].includes(s.phase)&&!editing;for(const [key,name]of Object.entries(strategyNames)){const tr=document.createElement('tr');if(s.forestStrategy===key)tr.className='selected-strategy';const result=forestCache?.find(r=>r[0]===key)?.[1];for(const text of [name+(s.forestStrategy===key?' · selected':''),reveal&&result?`${result.correction.length} edges`:'—',reveal&&result?.valid?'✓ matches':'—']){const td=document.createElement('td');td.textContent=text;tr.append(td);}body.append(tr);}
 $('forest-experiment-note').textContent=reveal?'Changing this choice rebuilds and peels the forest. Growth and its fully grown edge set stay identical.':'Advance to Forest to reveal the completed correction costs.';
 const chart=$('gap-diagram');chart.replaceChildren();if(reveal&&reference?.available&&grownReference?.available){const selected=forestCache.find(r=>r[0]===s.forestStrategy)[1].correction.length,max=Math.max(1,selected);for(const [label,n,cl]of [['Global minimum',reference.cost,'global'],['Grown-region min.',grownReference.cost,'region'],['Selected forest',selected,'']]){const row=document.createElement('div');row.className='gap-row';const lab=document.createElement('span');lab.textContent=label;const track=document.createElement('div');track.className='gap-track';const bar=document.createElement('div');bar.className='gap-bar '+cl;bar.style.width=n/max*100+'%';track.append(bar);const count=document.createElement('span');count.textContent=n;row.append(lab,track,count);chart.append(row);}}}
function queue(){let target=$('fusion-queue');if(!target){target=document.createElement('div');target.id='fusion-queue';target.className='round-queue';$('uf-panel-step').append(target);}target.replaceChildren();const {s}=latest;if(s.phase!=='grow'||!s.roundFullEdges?.length)return;const label=document.createElement('div');label.className='queue-label';label.textContent=`Round ${s.tick} fusion queue · ${s.roundFullEdges.length} completed edges`;const list=document.createElement('div');list.className='queue-list';const done=new Set(s.operations.map(o=>o.edge)),current=s.micro?s.operations.at(-1)?.edge:null;for(const eid of s.roundFullEdges){const chip=document.createElement('span');chip.className='queue-edge'+(done.has(eid)?' processed':'')+(eid===current?' current':'');chip.textContent=`e${eid}`;list.append(chip);}target.append(label,list);}
document.addEventListener('uf-state',e=>{latest=e.detail;const {s,graph,editing}=latest;const content=labels[graph.key]||labels.custom;$('graph-size').textContent=`${graph.nodes.length} vertices · ${graph.edges.length} edges`;$('lesson-title').textContent=content[0];$('lesson-goal').textContent=content[1];$('phase-name').textContent=editing?'EDIT SYNDROME':s.phase.toUpperCase();$('step-title').textContent=editing?'Set the input syndrome':s.title;$('step-intro').textContent=editing?'Select vertices on the graph, then choose Run decoder.':s.note;$('current-round').textContent=`ROUND ${s.tick}`;$('metric-active').textContent=s.groups.filter(g=>g.active).length;$('metric-residual').textContent=s.bits.reduce((a,b)=>a+b,0);$('metric-cost').textContent=s.correction.length;forestComparison();drawPath();residuals();queue();});
$('dsu-node').addEventListener('change',drawPath);
new ResizeObserver(()=>drawPath()).observe($('dsu-path'));
const tabs=[...document.querySelectorAll('[role=tab]')];function activate(tab){tabs.forEach(t=>{const selected=t===tab;t.classList.toggle('active',selected);t.setAttribute('aria-selected',String(selected));$(t.getAttribute('aria-controls')).hidden=!selected;});}tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>activate(tab));tab.addEventListener('keydown',e=>{let j=i;if(e.key==='ArrowRight')j=(i+1)%tabs.length;else if(e.key==='ArrowLeft')j=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')j=0;else if(e.key==='End')j=tabs.length-1;else return;e.preventDefault();tabs[j].focus();tabs[j].click();});});
})();
